version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Sirheribrine23

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - Sirheribrine23