version: "3.9"
volumes:
  MacOSDisks:
services:
  macos:
    build: .
    container_name: MacOSOnKVM
    volumes:
      - "MacOSDisks:/root"
    devices:
      - /dev/kvm
    environment:
      INSTALL_SYSTEM: "true"
      SYSTEM_NAME: "catalina"
      SYSTEM_SIZE: "250G"
    ports:
      - "5801:5801"
      - "5901:5901"