name: Build Binarie
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install depedencies
        run: npm install

      - name: Build bin
        run: npm run nexe

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: ".Build/*_binarie*"
          body: Linux, architecture ${{ matrix.arch }}

  win32:
    runs-on: windows-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.2.0

      - name: Install depedencies
        run: npm install

      - name: Build bin
        run: npm run nexe

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: ".Build/*_binarie*"
          body: Windows X64

  MacOS:
    runs-on: macos-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install depedencies
        run: npm install

      - name: Build bin
        run: npm run nexe

      - name: Releases
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          files: ".Build/*_binarie*"
          body: MacOS X64